name=Symbex
version=2.6.0
author=Carlos Eden
maintainer=CITEP
sentence=SYMBEX-1 K-bit Edge Inference Engine.
paragraph=Motor de inferencia de ultra-bajo recurso con Bit-Slicing y expansion topologica.
category=Data Processing
url=https://github.com
architectures=*
